GET http://localhost:1111/models







###
GET http://localhost:1111/models/default


###
GET http://localhost:1111/models/front


###
GET http://localhost:1111/models/default/logs

###
POST http://localhost:1111/models/default/refresh