GET http://localhost:1112/models


###
GET http://localhost:1112/models/front



###  deufault get 
GET http://localhost:1112/models/default


### default sources 
GET http://localhost:1111/models/default/modelSources

### default logs 
GET http://localhost:1112/models/default/logs

### refresh
POST http://localhost:1112/models/default/refresh